using Microsoft.AspNetCore.Mvc;
using CAT.AID.Models;
using System.Text.Json;
using iText.Kernel.Pdf;
using iText.Layout;
using iText.Layout.Element;
using iText.Layout.Properties;

namespace CAT.AID.Controllers
{
public class ReportController : Controller
{
private readonly ApplicationDbContext _context;


    public ReportController(ApplicationDbContext context)
    {
        _context = context;
    }

    public IActionResult AssessmentPdf(int id)
    {
        var assessment = _context.Assessments
            .Where(a => a.Id == id)
            .Select(a => new
            {
                a.Id,
                Candidate = a.Candidate.FullName,
                a.AssessmentResultJson
            })
            .FirstOrDefault();

        if (assessment == null)
            return NotFound();

        var results = string.IsNullOrWhiteSpace(assessment.AssessmentResultJson)
            ? new Dictionary<string, string>()
            : JsonSerializer.Deserialize<Dictionary<string, string>>(assessment.AssessmentResultJson);

        using var ms = new MemoryStream();
        var writer = new PdfWriter(ms);
        var pdf = new PdfDocument(writer);
        var doc = new Document(pdf);

        doc.Add(new Paragraph("NIEPID CVAT Assessment Report")
            .SetTextAlignment(TextAlignment.CENTER)
            .SetFontSize(18));

        doc.Add(new Paragraph($"Candidate: {assessment.Candidate}"));
        doc.Add(new Paragraph($"Assessment ID: {assessment.Id}"));
        doc.Add(new Paragraph(" "));

        float[] widths = { 70, 30 };
        Table table = new Table(widths);
        table.AddHeaderCell("Question");
        table.AddHeaderCell("Score");

        foreach (var item in results)
        {
            if (item.Key.StartsWith("SCORE_"))
            {
                string qId = item.Key.Replace("SCORE_", "");
                table.AddCell("Question " + qId);
                table.AddCell(item.Value);
            }
        }

        doc.Add(table);

        doc.Add(new Paragraph(" "));
        doc.Add(new Paragraph("Generated by NIEPID CVAT System"));

        doc.Close();

        return File(ms.ToArray(),
            "application/pdf",
            "AssessmentReport.pdf");
    }
}


}
