using QuestPDF.Fluent;
using QuestPDF.Infrastructure;
using QuestPDF.Helpers;

namespace CAT.AID.Web.Services.PDF
{
    public abstract class BasePdfTemplate : IDocument
    {
        protected readonly string Title;
        protected readonly string LogoLeft;
        protected readonly string LogoRight;

        protected BasePdfTemplate(string title, string logoLeft, string logoRight)
        {
            Title = title;
            LogoLeft = logoLeft;
            LogoRight = logoRight;

            QuestPDF.Settings.License = LicenseType.Community;
        }

        // REQUIRED by QuestPDF
        public DocumentMetadata GetMetadata() => DocumentMetadata.Default;

        // REQUIRED by QuestPDF
        public void Compose(IDocumentContainer container)
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(30);
                page.DefaultTextStyle(x => x.FontSize(10));

                page.Header().Element(Header);
                page.Content().Element(ComposeContent);
                page.Footer().AlignCenter().Text(x =>
                {
                    x.Span("Generated by CAT.AID • ");
                    x.CurrentPageNumber();
                    x.Span(" / ");
                    x.TotalPages();
                });
            });
        }

        // HEADER -------------------------------------------------
        private void Header(IContainer container)
        {
            container.Row(row =>
            {
                row.RelativeItem(1).Height(60).AlignLeft().Element(c =>
                {
                    if (File.Exists(LogoLeft))
                        c.Image(LogoLeft, ImageScaling.FitArea);
                });

                row.RelativeItem(2).AlignCenter().AlignMiddle().Text(Title)
                    .FontSize(16).Bold().FontColor(Colors.Blue.Darken2);

                row.RelativeItem(1).Height(60).AlignRight().Element(c =>
                {
                    if (File.Exists(LogoRight))
                        c.Image(LogoRight, ImageScaling.FitArea);
                });
            });
        }

        // 🔥 MUST be overridden by child PDFs
        protected abstract void ComposeContent(IContainer container);
    }
}
